package com.xialuo.shop.dao;

import com.xialuo.shop.domain.Coupon;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface CouponMapper {

  @Select("select * from coupon where id = #{id}")
  Map<String,Object> getCounponById(@Param("id") Long id);
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table coupon
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table coupon
   *
   * @mbggenerated
   */
  int insert(Coupon record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table coupon
   *
   * @mbggenerated
   */
  Coupon selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table coupon
   *
   * @mbggenerated
   */
  List<Coupon> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table coupon
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(Coupon record);
}